//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppColumn
    {
        public int AppColumnId { get; set; }
        public int AppTableId { get; set; }
        public string ColumnName { get; set; }
        public string DisplayName { get; set; }
        public string ElementType { get; set; }
        public int ElementWidth { get; set; }
        public int ElementHeight { get; set; }
        public int ColumnOrder { get; set; }
        public bool IsIdentity { get; set; }
        public bool IsRequired { get; set; }
        public bool IsComputed { get; set; }
        public bool IsPrimaryKey { get; set; }
        public int DataLength { get; set; }
        public string DefaultValue { get; set; }
        public string DataType { get; set; }
        public int SystemTypeId { get; set; }
    
        public virtual AppTable AppTable { get; set; }
    }
}
