//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDatabase
    {
        public int AppDatabaseId { get; set; }
        public int ClientId { get; set; }
        public string DatabaseName { get; set; }
        public string ConnectionString { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
