//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppTable()
        {
            this.AppColumns = new HashSet<AppColumn>();
        }
    
        public int AppTableId { get; set; }
        public int AppDatabaseId { get; set; }
        public string TableName { get; set; }
        public string PrimaryKey { get; set; }
        public string PrimaryKeyType { get; set; }
        public int SystemTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppColumn> AppColumns { get; set; }
        public virtual AppDatabase AppDatabase { get; set; }
    }
}
