//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DodoBirdEntities : DbContext
    {
        public DodoBirdEntities()
            : base("name=DodoBirdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu1Item> Menu1Item { get; set; }
        public virtual DbSet<Menu2Item> Menu2Item { get; set; }
        public virtual DbSet<Menu3Item> Menu3Item { get; set; }
        public virtual DbSet<AppDatabase> AppDatabases { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
    }
}
