//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu1Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu1Item()
        {
            this.Menu2Item = new HashSet<Menu2Item>();
        }
    
        public int Menu1ItemId { get; set; }
        public string MenuTitle { get; set; }
        public string PageFile { get; set; }
        public string TsScript { get; set; }
        public int GridId { get; set; }
        public int FormId { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu2Item> Menu2Item { get; set; }
    }
}
