//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu3Item
    {
        public int Menu3ItemId { get; set; }
        public int Menu2ItemId { get; set; }
        public string MenuTitle { get; set; }
        public string PageFile { get; set; }
        public string TsScript { get; set; }
        public int GridId { get; set; }
        public int FormId { get; set; }
        public int SortOrder { get; set; }
    }
}
