//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DodoBird.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageTemplate()
        {
            this.ColumnDefs = new HashSet<ColumnDef>();
        }
    
        public int PageTemplateId { get; set; }
        public int DbEntityId { get; set; }
        public string TemplateName { get; set; }
        public string TableName { get; set; }
        public string PrimaryKey { get; set; }
        public string ReportGridColumns { get; set; }
        public string GridColumns { get; set; }
        public string SortColumns { get; set; }
        public string AddTabLabel { get; set; }
        public string EditTabLabel { get; set; }
        public string Layout { get; set; }
        public string PageType { get; set; }
        public string FilterClause { get; set; }
        public int HelpId { get; set; }
        public string OnLoadScript { get; set; }
        public string BodyScript { get; set; }
        public string OnSaveScript { get; set; }
        public int PageTemplateId2 { get; set; }
        public int RefKey2 { get; set; }
        public int PrimaryKey2 { get; set; }
        public string GridBodyHTML { get; set; }
        public string GridScript { get; set; }
        public string GridCSS { get; set; }
        public string GridOnDataBound { get; set; }
        public string CustomEditForm { get; set; }
        public string GroupByColumns { get; set; }
        public bool GridAutoBind { get; set; }
        public string GridCommand { get; set; }
        public string RefKey2Name { get; set; }
        public string PrimaryKey2Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColumnDef> ColumnDefs { get; set; }
        public virtual DbEntity DbEntity { get; set; }
    }
}
